-- This file has be generated by Tricky's MyData
-- 31 Aug 2017; 15:24:55
-- License: Closed Lic

local

ret = {
	["CH1"] = {
		["LekkerWijf"] = "Vp][",
		["Punt"] = 10,
		["Storing"] = "Vp^C[Cm"},
	["CH2"] = {
		["LekkerWijf"] = "Vp'V",
		["Punt"] = 20,
		["Storing"] = "Vp^C[C%"},
	["CH3"] = {
		["LekkerWijf"] = "Vp'^",
		["Punt"] = 30,
		["Storing"] = "Vp^C[C)"},
	["CH4"] = {
		["LekkerWijf"] = "Vp'^",
		["Punt"] = 40,
		["Storing"] = "Vp^C[C["},
	["ZZA"] = {
		["LekkerWijf"] = "K6/",
		["Punt"] = 0,
		["Storing"] = "/er,7PLJ8!)yLeYLJYY!LP7Y,4%Ler)LdY7J%"},
	["ZZG"] = {
		["LekkerWijf"] = "VpOOV]t",
		["Punt"] = 0,
		["Storing"] = ")%Ok^^tPF$m'F$)kuCPmkFV[)ku]Ptmm"}}



-- Got all data, let's now return it!
return ret
